name: CI Pipeline with Stages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    name: "Unit Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "test 1"

  linter:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "test 2"

  type_test:
    name: "Type Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "test 3"

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: [unit_test, linter, type_test]  # Зависит от всех тестов
    if: github.event_name == 'push' || github.event.inputs.manual_trigger == 'true'
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./build.sh
      - run: ./build.sh
